version: '2'
services:

  django_beta:
    image: "icarussystem/asilinks:beta"
    build:
      context: .
      dockerfile: Dockerfile-devel
    container_name: django_beta
    hostname: asilinks
    network_mode: "bridge"
    ports: 
      - "8001:8080"
    external_links:
      - mongo
    env_file:
    - beta.env
    volumes:
      - ../:/asilinks_server
    working_dir: /asilinks_server/asilinks
    stdin_open: true
    tty: true
    command: django-admin runserver --pythonpath /asilinks_server/asilinks --settings asilinks.settings 0:8080

  others_beta:
    image: "icarussystem/asilinks:beta"
    build:
      context: .
      dockerfile: Dockerfile-devel
    container_name: others_beta
    hostname: others
    network_mode: "bridge"
    ports: 
      - "5555:8888"
    external_links:
      - mongo
    env_file:
    - beta.env
    volumes:
      - ../:/asilinks_server
      - ./jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
      - ./supervisord-devel.conf:/etc/supervisor/conf.d/supervisord.conf
    working_dir: /asilinks_server/notebooks
    command: /usr/bin/supervisord
