FROM joschsan/miniconda3:4.5.11

RUN apt-get update --fix-missing && \
	apt-get install -y build-essential supervisor \
		libssl-dev libffi-dev libcurl4-openssl-dev \
		libcairo2 libpango-1.0-0 libpangocairo-1.0-0 \
		libgdk-pixbuf2.0-0 shared-mime-info

RUN mkdir -p /root/.jupyter /var/log/supervisor

COPY requirements-devel.txt /root/

RUN pip install --upgrade pip && \
	pip --no-cache-dir install \
	-r /root/requirements-devel.txt

WORKDIR /

CMD ["bash"]
